export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const APP_LEVEL_ALERT_SHOW = 'APP_LEVEL_ALERT_SHOW';
export const APP_LEVEL_ALERT_HIDE = 'APP_LEVEL_ALERT_HIDE';

export const LOAD_GAMES_SUCCESS = 'LOAD_GAMES_SUCCESS';
export const LOAD_GAME_DETAILS_SUCCESS = 'LOAD_GAME_DETAILS_SUCCESS';
