apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello-mgr-ctlr
  name: othello-mgr-ctlr
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: othello-mgr-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello-mgr-ctlr
    spec:
      containers:
      - image: 10.110.88.214:5000/othello:1.0-mgr-ctr-amd64
        imagePullPolicy: Always
        name: othello-mgr
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
          - name: POD_IP
            valueFrom: 
              fieldRef:
                fieldPath: status.podIP
          - name: PG_HOST
            value: postgres-postgresql
          - name: PG_PORT
            value: "5432"
          - name: PG_USER
            value: postgres
          - name: PG_DBNAME
            value: postgres
          - name: SOLUTION_QUEUE_LENGTH
            value: "100"
          - name: PG_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-postgresql
                key: postgresql-password
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello-mgr-ctlr
  name: othello-mgr-ctlr
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: othello-mgr-ctlr
  sessionAffinity: None
  type: ClusterIP