apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello-mgr-ctlr
  name: othello-mgr-ctlr
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: othello-mgr-ctlr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello-mgr-ctlr
    spec:
      containers:
      - image: 10.110.88.214:5000/othello:1.0-mgr-ctr-amd64
        imagePullPolicy: Always
        name: othello-mgr
        ports:
        - containerPort: 9090
          protocol: TCP
        env:
          - name: POD_IP
            valueFrom: 
              fieldRef:
                fieldPath: status.podIP
          - name: MONGO_HOST
            value: mongosvc
          - name: MONGO_PORT
            value: "27017"
          - name: REDIS_RW
            value: othello-redis-master.default.svc.cluster.local
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: othello-redis
                key: redis-password
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello-mgr-ctlr
  name: othello-mgr-ctlr
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: othello-mgr-ctlr
  sessionAffinity: None
  type: ClusterIP