apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello
  name: othello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: othello
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello
    spec:
      containers:
      - image: randysimpson/othello:1.0-server-latest
        imagePullPolicy: IfNotPresent
        name: othello
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello
  name: othello-server
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30563
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: othello
  sessionAffinity: None
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello-random-ai
  name: othello-random-ai
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: othello-random-ai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello-random-ai
    spec:
      containers:
      - image: randysimpson/othello:1.0-random-latest
        imagePullPolicy: IfNotPresent
        name: othello
        ports:
        - containerPort: 10000
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello-random-ai
  name: othello-random-ai
spec:
  ports:
  - port: 10000
    protocol: TCP
    targetPort: 10000
  selector:
    app: othello-random-ai
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello-greedy-ai
  name: othello-greedy-ai
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: othello-greedy-ai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello-greedy-ai
    spec:
      containers:
      - image: randysimpson/othello:1.0-greedy-latest
        imagePullPolicy: IfNotPresent
        name: othello
        ports:
        - containerPort: 9000
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello-greedy-ai
  name: othello-greedy-ai
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: othello-greedy-ai
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello-custom-ai
  name: othello-custom-ai
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: othello-custom-ai
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello-custom-ai
    spec:
      containers:
      - image: randysimpson/othello:1.0-custom-ai-latest
        imagePullPolicy: IfNotPresent
        name: othello
        ports:
        - containerPort: 9000
          protocol: TCP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello-custom-ai
  name: othello-custom-ai
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: othello-custom-ai
  sessionAffinity: None
  type: ClusterIP
