#this is the user and password config.
apiVersion: v1
data:
  postgres_host: postres
  postgres_password: jdMc%Ejdi1Vcs2dTe#oc9TCfnc
  postgres_user: othello-engine
kind: ConfigMap
metadata:
  name: pgconfig
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
      version: 12.1.0
  template:
    metadata:
      labels:
        app: postgres
        version: 12.1.0
    spec:
      volumes:
      - name: postgresdb
        hostPath:
          path: /data/pgdb
      containers:
      - name: postgres
        image: postgres:12.1
        ports:
          - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: pgconfig
              key: postgres_password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: /var/lib/postgresql/data/
          name: postgresdb
---
apiVersion: v1
kind: Service
metadata:
  name: postgressvc
  labels:
    name: postgressvc
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: postgres