apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: othello-gen
  name: othello-gen
spec:
  replicas: 6
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: othello-gen
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: othello-gen
    spec:
      containers:
      - image: 10.110.88.214:5000/othello:1.0-generator-amd64
        imagePullPolicy: Always
        name: othello-mgr
        ports:
        - containerPort: 8080
          protocol: TCP
        env:
          - name: POD_IP
            valueFrom: 
              fieldRef:
                fieldPath: status.podIP
          - name: MGR_HOST
            value: othello-mgr-ctlr
          - name: MGR_PORT
            value: "9090"
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: othello-gen
  name: othello-gen
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: othello-gen
  sessionAffinity: None
  type: ClusterIP